### PR TITLE
Updated French-language translations

### PR DESCRIPTION
**Pull request by dxniel-19**
Added and corrected a few lines.

### CODE REVIEW

**Comment by RussCoder** [comment]
Why didn't you translate other `null` phrases? They all need to be translated, but you translated only 3 of them.

**Comment by dxniel-19** [comment]
Was planning on adding some over time. They are all done now.

**Comment by RussCoder** [comment]
Well done 👍

**Comment by RussCoder** [comment]
If you want to be notified when there are new phrases that need to be translated, subscribe to this discussion, please: 
https://github.com/RussCoder/djvujs/discussions/63

**Pull request merged**
