### PR TITLE
Italian Translation File - v1.3

### PR DESCRIPTION
**Pull request by aamodio**
Italian Translation File - v1.3 - Minor changes to print function strings

### CODE REVIEW

**Comment by RussCoder** [comment]
Your branch has conflicts with the master. 
You should sync your repository with mine (because when I merge PRs I often squash several commits into one, not merge your commits directly, so eventually there are different set of commits in our branches).  

If you followed this 
https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/configuring-a-remote-for-a-fork
and the my repo is named "upstream", that is you have run:

```
git remote add upstream https://github.com/RussCoder/djvujs.git
```
then the following steps may help you:

```
git fetch upstream 
git checkout master
git reset --hard upstream/master
git push --force
```

But you **will lose all your changes** in your repository after this, so save them into a file before doing it.

**Comment by RussCoder** [comment]
@aamodio I'm going to publish a new release (today or tomorrow) with the fix for the issue you recently opened. And I would like to include this translation update into it. So either resolve the conflicts, please, or I will just copy your changes and add them manually.

**Comment by RussCoder** [comment]
I cherry-picked your latest commit to the master.

**Comment by aamodio** [comment]
Sorry, I'm not very practical with GitHub.
Thank you for your manual pull of my code.

**Pull request closed without merging**
